### ISSUE TITLE
Minor Error. Amp Code

### ISSUE THREAD

**Issue by kalverra** [Cristianasp/prj-rev-bwfs-dasmoto#1]
https://github.com/Cristianasp/prj-rev-bwfs-dasmoto/blob/master/Projeto%20Arts/index.html#L12

& is a special character in HTML, check here. http://rabbit.eng.miami.edu/info/htmlchars.html

**Comment by Cristianasp** [comment]
Thanks, I haven´t even noticed this special character. Done.
