### ISSUE TITLE
Simplify. Indentation

### ISSUE THREAD

**Issue by kalverra** [Cristianasp/prj-rev-bwfs-dasmoto#2]
https://github.com/Cristianasp/prj-rev-bwfs-dasmoto/blob/master/Projeto%20Arts/index.html#L4-L28

Work on your indentation, as it seems there is none. It's critical for organization of your code. https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/ and https://google.github.io/styleguide/htmlcssguide.html

**Comment by Cristianasp** [comment]
ok. got it.
