### ISSUE TITLE
Simplify. Capital Tags

### ISSUE THREAD

**Issue by kalverra** [Cristianasp/prj-rev-bwfs-dasmoto#4]
https://github.com/Cristianasp/prj-rev-bwfs-dasmoto/blob/master/Projeto%20Arts/index.html#L17-L27

The capital <P> tag is a big nono generally. Check out Google's style guide for formatting things. https://google.github.io/styleguide/htmlcssguide.html

**Comment by Cristianasp** [comment]
ok. done.
